### ISSUE TITLE
mql_finance: warning error

### ISSUE THREAD

**Issue by lawnn** [nagishin/DataUtility#3]
タイトルの件で警告がでました。
下記のとおり警告がでます。

C:\Users\user\Anaconda3\lib\site-packages\mpl_finance.py:16: DeprecationWarning: 

  =================================================================

   WARNING: `mpl_finance` is deprecated:

    Please use `mplfinance` instead (no hyphen, no underscore).

    To install: `pip install --upgrade mplfinance` 

   For more information, see: https://pypi.org/project/mplfinance/

  =================================================================

  __warnings.warn('\n\n  ================================================================='+

解決策
少し調べてみたところ旧matplotlib/mpl-financeは2020年に終了したのでmatplotlib/mplfinanceに変更する必要があるようです。

# install
pip install --upgrade mplfinance

# before
import mpl_finance as mqf

# after
import mplfinance.original_flavor as mqf

**Comment by nagishin** [comment]
アップして間もないクラスをご確認頂き、ありがとうございます。
ご提示頂いた解決策を確認し、ver1.1.1で修正をコミットしました。
お手数ですが、アップデートをお願い致します。

**Comment by lawnn** [comment]
お手数かけてすみません。
アップデートして動作確認したところ警告はでなくなりました。
早速の修正ありがとうございます。
