### ISSUE TITLE
save_daily_ohlcv_from_bybit_trading_gz 関数の ValueError

### ISSUE THREAD

**Issue by lawnn** [nagishin/DataUtility#5]
```
ValueError: cannot safely convert passed user dtype of int32 for float64 dtyped data in column 3
```
symbolをBTCUSDTで取得しようとすると上記のエラーがでました。
column 3　は sizeでした
それぞれcsv.gzのsizeの中身は下記のとおりで
```
BTCUSD　int型    100などの数字
BTCUSDT　float型   0.042などの数字
```
自分の方では1856行目のdtypeをあえて指定しないように修正しましたが
各個人のpythonの環境（Python2かPython3か、32ビットか64ビットかなど）によっては違うものになるかもしれないです。
（python2使ってる人は居ないと思いますがｗ）
[https://note.nkmk.me/python-pandas-dtype-astype/](url)
[https://github.com/nagishin/DataUtility/blob/6811322963b8c19abaf6f327e730c187ceb7589d/DataUtility/tool.py#L1856](url)

下のように修正しました。
修正前
```
dtype={'timestamp':'float', 'side':'str', 'price':'float', 'size':'int'})
```
修正後
```
dtype={'timestamp':'float', 'side':'str', 'price':'float'})
```

**Comment by nagishin** [comment]
ご指摘ありがとうございます。
仰るとおりsizeは
```
BTCUSD -> USD (int)
BTCUSDT -> BTC (float)
```
になりますね。
上記より修正内容も適切だと思いますのでToolクラスに適用させて頂きます。

**Comment by lawnn** [comment]
修正ありがとうございました。
解決したのでissues閉じます。
